name: 'Liquibase Validation'
description: 'Check if a liquibase script has -- liquibase-format and -- changeset instructions'
inputs:
  file:  # filename to read
    description: 'the filename o read'
    required: true
outputs:
  validFiles: # id of output
    description: 'Array of valid Files'
  invalidFiles: # id of output
    description: 'Array of invalid Files'
runs:
  using: 'node16'
  main: 'dist/index.js'
